CREATE TABLE _pages (
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
	insTime TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
	title VARCHAR(30) UNIQUE NOT NULL,
	htmlCode TEXT,
	img BLOB,
	visits INTEGER NOT NULL DEFAULT 0,
	author VARCHAR(20) NOT NULL,
	posted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE _modifiedPages (
	ID INTEGER,
	modTime TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
	htmlCode TEXT,
	img BLOB,
	type1 VARCHAR(11),
	type2 VARCHAR(18),
	
	PRIMARY KEY (ID,modTime),
	
	FOREIGN KEY (ID) REFERENCES _pages(ID)
					ON DELETE CASCADE
					ON UPDATE CASCADE
);

CREATE TABLE _characters (
	ID INTEGER PRIMARY KEY,
	type VARCHAR(17) NOT NULL,
	
	FOREIGN KEY (ID) REFERENCES _pages(ID)
					ON DELETE CASCADE
					ON UPDATE CASCADE
);

CREATE TABLE _events (
	ID INTEGER PRIMARY KEY,
	era VARCHAR(12) NOT NULL,
	
	FOREIGN KEY (ID) REFERENCES _pages(ID)
					ON DELETE CASCADE
					ON UPDATE CASCADE
);

CREATE TABLE _places (
	ID INTEGER PRIMARY KEY,
	mythological BOOLEAN,
	
	FOREIGN KEY (ID) REFERENCES _pages(ID)
					ON DELETE CASCADE
					ON UPDATE CASCADE
);

CREATE TABLE _relations (
	ID1 INTEGER,
	ID2 INTEGER,
	PRIMARY KEY(ID1,ID2),
	
	FOREIGN KEY (ID1) REFERENCES _pages(ID)
					ON DELETE CASCADE
					ON UPDATE CASCADE,
	FOREIGN KEY (ID2) REFERENCES _pages(ID)
					ON DELETE CASCADE
					ON UPDATE CASCADE
);