CREATE TABLE _users (
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
	username VARCHAR(25) UNIQUE NOT NULL,
	name VARCHAR(25),
	surname VARCHAR(25),
	birthDate DATE,
	gender ENUM('M','F'),
	email VARCHAR(40),
	pass_word CHAR(40),
	is_admin BOOLEAN
);

CREATE TABLE _pages (
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
	insTime TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
	title VARCHAR(30) UNIQUE NOT NULL,
	content TEXT,
	img LONGBLOB,
	visits INTEGER NOT NULL DEFAULT 0,
	author INTEGER,
	posted BOOLEAN NOT NULL DEFAULT FALSE,
	
	FOREIGN KEY (author) REFERENCES _users(ID)
			ON DELETE SET NULL
			ON UPDATE CASCADE
);

CREATE TABLE _modifiedPages (
	ID INTEGER,
	modTime TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
	content TEXT,
	img LONGBLOB,
	type1 VARCHAR(11),
	type2 VARCHAR(18),
	
	PRIMARY KEY (ID,modTime),
	
	FOREIGN KEY (ID) REFERENCES _pages(ID)
					ON DELETE CASCADE
					ON UPDATE CASCADE
);

CREATE TABLE _characters (
	ID INTEGER PRIMARY KEY,
	type VARCHAR(17) NOT NULL,
	
	FOREIGN KEY (ID) REFERENCES _pages(ID)
					ON DELETE CASCADE
					ON UPDATE CASCADE
);

CREATE TABLE _events (
	ID INTEGER PRIMARY KEY,
	era VARCHAR(12) NOT NULL,
	
	FOREIGN KEY (ID) REFERENCES _pages(ID)
					ON DELETE CASCADE
					ON UPDATE CASCADE
);

CREATE TABLE _places (
	ID INTEGER PRIMARY KEY,
	type VARCHAR(10),
	
	FOREIGN KEY (ID) REFERENCES _pages(ID)
					ON DELETE CASCADE
					ON UPDATE CASCADE
);

CREATE TABLE _relations (
	ID1 INTEGER,
	ID2 INTEGER,
	PRIMARY KEY(ID1,ID2),
	
	FOREIGN KEY (ID1) REFERENCES _pages(ID)
					ON DELETE CASCADE
					ON UPDATE CASCADE,
	FOREIGN KEY (ID2) REFERENCES _pages(ID)
					ON DELETE CASCADE
					ON UPDATE CASCADE
);

CREATE TABLE _pendantRelations(
	ID1 INTEGER,
	ID2 INTEGER,
	modTime TIMESTAMP(6),
	PRIMARY KEY(ID1,ID2,modTime),
	
	FOREIGN KEY (ID1) REFERENCES _pages(ID)
					ON DELETE CASCADE
					ON UPDATE CASCADE,
	FOREIGN KEY (ID2) REFERENCES _pages(ID)
					ON DELETE CASCADE
					ON UPDATE CASCADE
);

CREATE TABLE _comments(
	pageID INTEGER NOT NULL,
	time_stamp TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
	content TEXT,
	author INTEGER DEFAULT -1,
	
	PRIMARY KEY (pageID,time_stamp,author),
	
	FOREIGN KEY (pageID) REFERENCES _pages (ID)
					ON DELETE CASCADE
					ON UPDATE CASCADE,
	FOREIGN KEY (author) REFERENCES _users (ID)
					ON DELETE CASCADE
					ON UPDATE CASCADE
);